// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SIUAK2H1cHao_3GcMQCgXvTIZWNzV2Y',
    appId: '1:954160440100:web:ebe3a662748bea7863c9b1',
    messagingSenderId: '954160440100',
    projectId: 'dham-gator-food-finder',
    authDomain: 'dham-gator-food-finder.firebaseapp.com',
    storageBucket: 'dham-gator-food-finder.firebasestorage.app',
    measurementId: 'G-ENMDWLCVWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDXb3PoUV_9191T3hOkliGc74nTp92Vo',
    appId: '1:954160440100:android:1a6d3e191107092d63c9b1',
    messagingSenderId: '954160440100',
    projectId: 'dham-gator-food-finder',
    storageBucket: 'dham-gator-food-finder.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SIUAK2H1cHao_3GcMQCgXvTIZWNzV2Y',
    appId: '1:954160440100:web:2968b60606b0048963c9b1',
    messagingSenderId: '954160440100',
    projectId: 'dham-gator-food-finder',
    authDomain: 'dham-gator-food-finder.firebaseapp.com',
    storageBucket: 'dham-gator-food-finder.firebasestorage.app',
    measurementId: 'G-RN9HC4NW6G',
  );
}
