# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - DHAM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Add Flutter setup
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # Build backend
      - name: npm install and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present

      # Build Flutter web
      - name: Build Flutter web
        run: |
          cd frontend
          flutter pub get
          flutter build web --release

      # Copy Flutter build to backend public folder
      - name: Copy Flutter web to backend
        run: |
          mkdir -p backend/public
          cp -r frontend/build/web/* backend/public/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B674949FBEFA481C9D971E08CCA3DA1C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_884A6BB4B1F745D4BFA00D160D90165E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_89A55F791622410D86059AF36356EE03 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DHAM'
          slot-name: 'Production'
          package: .